function stats = run_PFC_verified(duration)
% Run the supplied Simscape PFC model and verify the final ten line cycles.
% Usage: run_PFC_verified       (2 s); run_PFC_verified(1) (quick comparison).
% Requires MATLAB, Simulink, Simscape and Simscape Electrical (R2025b tested).
if nargin<1, duration=2; end
assert(duration>=1 && abs(duration/.02-round(duration/.02))<1e-8,...
    'Duration must be >= 1 s and an integer number of 20 ms line cycles.');
folder=fileparts(mfilename('fullpath'));
load_system(fullfile(folder,'PFC_verified.slx'));
out=sim('PFC_verified','StopTime',num2str(duration));
[stats,wave]=pfc_metrics(out.logsout,5e-5);
save(fullfile(folder,'verification_data.mat'),'stats','wave');
writetable(struct2table(stats),fullfile(folder,'verification_metrics.csv'));
pfc_plot(out.logsout,'PFC verified: 20 kHz, PI + feedforward',fullfile(folder,'corrected.png'),5e-5);
assert(stats.Pass,'PFC verification failed: inspect the metrics and waveforms.');
fprintf('PASS: PF %.5f, THD(2..40) %.2f%%, IL tracking %.2f%%, Vdc %.2f V\n',...
    stats.PF,stats.THD40_pct,stats.Tracking_pct,stats.Vdc);
end


function [s,w]=pfc_metrics(logs,switchPeriod)
if nargin<2, switchPeriod=1e-4; end
modern=ismember('Vout',logs.getElementNames);
if modern, e=logs.getElement('Vout'); else, e=logs.getElement('root_34_1'); end
tEnd=e.Values.Time(end);
dt=1e-6; t=(tEnd-0.2:dt:tEnd-dt)';
ids={'root_16_1','root_14_1','root_38_1','CurrentReference','root_34_1','PWMUpdateDelay'};
if modern, ids={'VAC','IAC','IL','Iref','Vout','Duty'}; end
% Names are generated by matlab.lang.makeValidName (spaces are camel-cased).
for k=1:numel(ids)
 e=logs.getElement(ids{k});
 [ut,ix]=unique(e.Values.Time,'last');
 w(:,k)=interp1(ut,double(e.Values.Data(ix)),t,'linear');
end
v=w(:,1); i=w(:,2); il=w(:,3); ref=w(:,4); vo=w(:,5);
samples=round(switchPeriod/dt);
avg=@(x)mean(reshape(x,samples,[]),1)';
ila=avg(il); ra=avg(ref);
s.Vdc=mean(vo); s.Vdc_pp=max(vo)-min(vo);
s.PF=mean(v.*i)/sqrt(mean(v.^2)*mean(i.^2));
s.Pin=mean(v.*i); s.Pout=mean(vo.^2)/80;
s.ILavg_RMSE=sqrt(mean((ila-ra).^2));
s.Tracking_pct=100*s.ILavg_RMSE/sqrt(mean(ra.^2));
s.Iref_rms=sqrt(mean(ref.^2)); s.IL_rms=sqrt(mean(il.^2));
amp=zeros(40,1);
for n=1:40
 amp(n)=2*abs(mean(i.*exp(-1i*2*pi*50*n*t)));
end
s.THD40_pct=100*norm(amp(2:end))/amp(1);
s.Current_phase_deg=angle(mean(i.*exp(-1i*2*pi*50*t))/mean(v.*exp(-1i*2*pi*50*t)))*180/pi;
s.SwitchRipple_pp_median=median(max(reshape(il,samples,[]),[],1)-min(reshape(il,samples,[]),[],1));
s.Analysis_start=tEnd-0.2; s.Analysis_end=tEnd;
s.Pass=s.Tracking_pct<5 && s.PF>0.99 && abs(s.Vdc-400)<4 && s.THD40_pct<5;
disp(s); w=[t,w];
end

function pfc_plot(logs,label,destination,switchPeriod)
if nargin<4, switchPeriod=1e-4; end
[~,w]=pfc_metrics(logs,switchPeriod); tEnd=w(end,1)+1e-6;
samples=round(switchPeriod/1e-6);
f=figure('Visible','off','Color','w','Theme','light','Position',[100 100 1300 1000]);
tiledlayout(4,1,'TileSpacing','compact');
nexttile; plot(w(:,1),w(:,2)/311,'Color',[.1 .3 .7]); hold on;
plot(w(:,1),w(:,3)/max(abs(w(:,3))),'Color',[.8 .25 .1]);
xlim([tEnd-.04 tEnd]); grid on; ylabel('Normalized'); legend('VAC / 311 V','IAC / peak'); title(label,'Interpreter','none');
nexttile; plot(w(:,1),w(:,4),'Color',[.7 .7 .7]); hold on;
plot(w(:,1),w(:,5),'r','LineWidth',1.2);
plot(mean(reshape(w(:,1),samples,[]),1),mean(reshape(w(:,4),samples,[]),1),'b');
xlim([tEnd-.04 tEnd]); grid on; ylabel('Current (A)'); legend('IL instantaneous','Iref','IL switching-cycle average');
nexttile; plot(w(:,1),w(:,4)); hold on; plot(w(:,1),w(:,5),'r','LineWidth',1.2);
xlim([tEnd-.016 tEnd-.015]); grid on; ylabel('Current (A)'); legend('IL','Iref');
nexttile;
if ismember('Vout',logs.getElementNames), e=logs.getElement('Vout'); else, e=logs.getElement('root_34_1'); end
plot(e.Values.Time,e.Values.Data); hold on; yline(400,'r--');
grid on; ylabel('Vout (V)'); xlabel('Time (s)'); xlim([0 tEnd]);
exportgraphics(f,destination,'Resolution',130); close(f);
end

